### PR TITLE
PLEASE REVIEW.

### PR DESCRIPTION
**Pull request by 122004**
Trying out a drivetrain, please feel free to correct my many mistakes. Thanks!

### CODE REVIEW

**Comment by 122004** [comment]
If someone could review and approve this that would be fantastic

**Comment by 122004** [comment]
So apparently there's a space inside my "Set Inverted" section. I can assure you that this is not in the code, i have no idea why it was included in this representation of my push. Help? This needs to be fixed!

**Review by Linkd-Aether — APPROVED** [review]
Looks like a good setup for drivetrain!

**Review by hallettc — APPROVED** [review]
looks good

**Pull request merged**
