### PR TITLE
Rumbles for Endgame & Getting Hit in Sandstorm

### PR DESCRIPTION
**Pull request by 122004**
Yet to be tested. If the robot is pushed to the right the controller vibrates in the right rumble, same for left. Also rumbles left/right/left/right at the start of endgame.

### CODE REVIEW

**Comment by 122004** [comment]
Nevermind it was tested! Please approve. 👍

**Comment by kcjesse02** [comment]
very nice

**Review by Linkd-Aether — APPROVED** [review]
Thank you.

-Nack

**Review by BenWertz — APPROVED** [review]
Neato.

**Pull request merged**
